# Generated by Django 5.1.3 on 2025-01-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="order_type",
            field=models.CharField(default="MARKET", max_length=20),
        ),
    ]
