# Generated by Django 5.1.3 on 2025-01-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptos", "0004_alter_orders_is_buy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLimitBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "limit_balance",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("currency", models.CharField(default="USDT", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_limit_balance",
                "indexes": [
                    models.Index(fields=["user"], name="user_limit__user_id_3317ad_idx")
                ],
            },
        ),
    ]
