# Generated by Django 5.1.3 on 2025-01-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptos", "0005_userlimitbalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="executed_price",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
