# Generated by Django 5.1.3 on 2025-01-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cryptos", "0006_orders_executed_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="executed_price",
        ),
    ]
