# Generated by Django 5.1.3 on 2025-01-10 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptos", "0007_remove_orders_executed_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="orders",
            name="orders_user_id_f22c5a_idx",
        ),
        migrations.AddIndex(
            model_name="orders",
            index=models.Index(
                fields=["user", "status"], name="orders_user_id_17dbdf_idx"
            ),
        ),
    ]
