# Generated by Django 5.1.3 on 2025-01-10 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptos", "0008_remove_orders_orders_user_id_f22c5a_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbalance",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
