# Generated by Django 5.1.3 on 2025-01-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cryptos", "0009_alter_userbalance_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbalance",
            options={"ordering": ["-updated_at"]},
        ),
    ]
