# Generated by Django 5.1.3 on 2025-01-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cryptos", "0010_alter_userbalance_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candlestick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("low", models.FloatField()),
                ("high", models.FloatField()),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cryptos.cryptosymbols",
                    ),
                ),
            ],
            options={
                "db_table": "candlestick",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"], name="symbol_timestamp_idx"
                    )
                ],
            },
        ),
    ]
