# Generated by Django 5.1.3 on 2025-01-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candlestick", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candlestick",
            name="volume",
            field=models.FloatField(default=0),
        ),
    ]
