# Generated by Django 5.1.3 on 2025-01-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candlestick", "0002_candlestick_volume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candlestick",
            options={"ordering": ["timestamp"]},
        ),
    ]
